# Manually maintained list of projects to feature on the home page.
#
# All other project references in the app can be derived from API calls dynamically.
#
# Note that descriptions here are provided instead of being pulled from the API because
# the ones from the API are usually too short -- the blurb on the upper-right hand side
# under "About"
#
# Available project config keys
#  - github: the `username/repo` pair, joined by a slash
#  - description: manual text about the featured package
#
featured_projects:
  - github: CrowdStrike/falcon-operator
    description: |
      The CrowdStrike Falcon Operator deploys CrowdStrike Falcon Workload Protection
      to the cluster. The operator exposes 2 custom resources that allows you to deploy
      either the Falcon Container Sensor or Falcon Node Sensor.

  - github: CrowdStrike/ember-browser-services
    description: |
      A collection of Ember Services that allow for consistent and convenient interaction with browser APIs,
      all powered by ember-window-mock.
      When all browser APIs are accessed via services, browser behavior is stubbable in unit tests.

  - github: CrowdStrike/falconpy
    description: |
      The FalconPy SDK contains a collection of Python classes that abstract
      CrowdStrike Falcon OAuth2 API interaction, removing duplicative code
      and allowing developers to focus on just the logic of their solution requirements.

