name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: Lint
        run: pnpm lint
        working-directory: site


  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: Run Tests
        run: pnpm test
        working-directory: site

  publish:
    name: Publish Docs to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    outputs:
      url: ${{ steps.publishStep.outputs.url }}
      env: ${{ steps.publishStep.outputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm
      - name: 'Refresh JSON data'
        run: pnpm build
      - name: Build App
        run: pnpm build
        working-directory: site
      - name: Publish to Cloudflare Pages
        id: publishStep
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.UX_OSS_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.UX_OSS_CLOUDFLARE_ACCOUNT_ID }}
          projectName: opensource-crowdstrike-com
          directory: ./site/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}


  publish_comment:
    name: Post Preview URL as comment to PR
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |+
            ## Preview URL
            ${{ needs.publish.outputs.url }}

